export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const UPLOAD_IMAGE_BEGIN = "UPLOAD_IMAGE_BEGIN";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POST_BEGIN = "GET_POST_BEGIN";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";

export const EDIT_POST_BEGIN = "EDIT_POST_BEGIN";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const GET_HOME_POST_BEGIN = "GET_HOME_POST_BEGIN";
export const GET_HOME_POST_SUCCESS = "GET_HOME_POST_SUCCESS";

export const FOLLOW_USER_BEGIN = "FOLLOW_USER_BEGIN";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_ERROR = "FOLLOW_USER_ERROR";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_RECOMMEND_USER_BEGIN = "GET_RECOMMEND_USER_BEGIN";
export const GET_RECOMMEND_USER_SUCCESS = "GET_RECOMMEND_USER_SUCCESS";
export const GET_RECOMMEND_USER_ERROR = "GET_RECOMMEND_USER_ERROR";

export const GET_REQUEST_USER_BEGIN = "GET_REQUEST_USER_BEGIN";
export const GET_REQUEST_USER_SUCCESS = "GET_REQUEST_USER_SUCCESS";
export const GET_REQUEST_USER_ERROR = "GET_REQUEST_USER_ERROR";

export const ADD_COMMENT_BEGIN = "ADD_COMMENT_BEGIN";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT_BEGIN";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

export const BEGIN = "BEGIN";
export const SUCCESS = "SUCCESS";
export const ERROR = "ERROR";

export const SWITCH_RIGHT = "SWITCH_RIGHT";

export const TOGGLE_RIGHT = "TOGGLE_RIGHT";
